/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query GetNotifications {\n    unreadNotificationsCount\n    notifications(first: 10) {\n      data {\n        id\n        read_at\n        created_at\n        data {\n          title\n          body\n          action_url\n          type\n        }\n      }\n    }\n  }\n": typeof types.GetNotificationsDocument,
    "\n  mutation MarkNotificationAsRead($id: ID!) {\n    markNotificationAsRead(id: $id) {\n      id\n      read_at\n    }\n  }\n": typeof types.MarkNotificationAsReadDocument,
    "\n  mutation MarkAllNotificationsAsRead {\n    markAllNotificationsAsRead\n  }\n": typeof types.MarkAllNotificationsAsReadDocument,
    "\n  query GetMe {\n    me {\n      id\n      email\n      phone\n      applicants {\n        id\n        firstName\n        middleNames\n        lastName\n        email\n        phone\n      }\n      students {\n        id\n        status\n      }\n      admins {\n        id\n      }\n      lecturers {\n        id\n      }\n    }\n  }\n": typeof types.GetMeDocument,
    "\n query GetAdminAccounts($first: Int = 100) { admins(first: $first) { edges { node { id employeeNumber department position createdAt updatedAt user { id } } } } }\n": typeof types.GetAdminAccountsDocument,
    "\n  query GetAdminDashboardData($first: Int = 100) {\n    registeredStudents: students(status: REGISTERED, first: $first) {\n      edges { node { id } }\n    }\n    pendingApplications: students(status: PENDING, first: $first) {\n      edges { node { id } }\n    }\n    schools(first: $first) {\n      edges { node { id } }\n    }\n    programs(first: $first) {\n      edges { node { id } }\n    }\n  }\n": typeof types.GetAdminDashboardDataDocument,
    "\n fragment AnnouncementFields on Announcement { id title content type targetLevel targetId targetName author authorUser { id } attachment { id\n          originalName\n          mimeType\n          size\n          url\n          collection\n          createdAt } createdAt updatedAt }\n": typeof types.AnnouncementFieldsFragmentDoc,
    "\n query GetAnnouncementsList($type: AnnouncementType, $targetLevel: TargetLevel, $first: Int!) { announcements(type: $type, targetLevel: $targetLevel, first: $first) { edges { node { ...AnnouncementFields } } pageInfo { hasNextPage endCursor } } }\n \n": typeof types.GetAnnouncementsListDocument,
    "\n query GetAnnouncementTargetOptions { schools(first: 100) { edges { node { id name } } } programs(first: 100) { edges { node { id title school { id name } } } } }\n": typeof types.GetAnnouncementTargetOptionsDocument,
    "\n  query GetLecturerDetails($id: ID!) {\n    lecturer(id: $id) {\n      id\n      firstName\n      middleName\n      lastName\n      dob\n      address\n      emergencyContact\n      createdAt\n      updatedAt\n      school {\n        id\n        name\n      }\n      user {\n        id\n        email\n      }\n      curricula {\n        id\n        year\n        program {\n          id\n          title\n          code\n        }\n        course {\n          id\n          code\n          title\n          credits\n        }\n      }\n    }\n  }\n": typeof types.GetLecturerDetailsDocument,
    "\n  fragment ManagementSchoolFields on School {\n    id\n    name\n    description\n    dean {\n      id\n      email\n    }\n  }\n": typeof types.ManagementSchoolFieldsFragmentDoc,
    "\n  query GetManagement($first: Int = 100) {\n    schools(first: $first) {\n      edges {\n        node {\n          ...ManagementSchoolFields\n        }\n      }\n    }\n  }\n  \n": typeof types.GetManagementDocument,
    "\n  query GetProgramDetail($id: ID!) {\n    program(id: $id) {\n      id\n      code\n      title\n      level\n      durationValue\n      durationUnit\n      shortDescription\n      longDescription\n      createdAt\n      updatedAt\n      requirements {\n        id\n        description\n        sortOrder\n      }\n      curricula {\n        id\n        year\n        course {\n          id\n          title\n          code\n          credits\n          school {\n            id\n            name\n          }\n        }\n        lecturer {\n          id\n          firstName\n          middleName\n          lastName\n          school {\n            id\n            name\n          }\n        }\n      }\n      school {\n        id\n        name\n      }\n    }\n  }\n": typeof types.GetProgramDetailDocument,
    "\n  query GetAllCourses($first: Int = 1000) {\n    courses(first: $first) {\n      edges {\n        node {\n          id\n          code\n          title\n          credits\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetAllCoursesDocument,
    "\n  query GetAllLecturers($first: Int = 1000) {\n    lecturers(first: $first) {\n      edges {\n        node {\n          id\n          firstName\n          middleName\n          lastName\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetAllLecturersDocument,
    "\n  query GetResultsPage($first: Int = 100) {\n    courses(first: $first) {\n      edges {\n        node {\n          id\n          code\n          title\n          curricula {\n            id\n            year\n            assessments {\n              id\n              title\n              type\n              term\n              maxScore\n              weightPercentage\n              dueDate\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetResultsPageDocument,
    "\n  query GetSchoolDetails($id: ID!) {\n    school(id: $id) {\n      id\n      name\n      description\n      dean {\n        id\n        email\n      }\n      programs {\n        id\n        code\n        title\n        level\n        durationValue\n        durationUnit\n        shortDescription\n      }\n      courses {\n        id\n        code\n        title\n        description\n        credits\n      }\n      lecturers {\n        id\n        firstName\n        middleName\n        lastName\n        user {\n          id\n          email\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetSchoolDetailsDocument,
    "\n  query GetStudentDetails($id: ID!) {\n    student(id: $id) {\n      id\n      applicationNumber\n      admissionNumber\n      studentNumber\n      firstName\n      middleNames\n      lastName\n      email\n      phone\n      dob\n      address\n      emergencyContact\n      sex\n      maritalStatus\n      nationality\n      nrcNumber\n      passportNumber\n      intake\n      studyMode\n      status\n      cgpa\n      creditsCompleted\n      applicationDate\n      admissionDate\n      rejectionDate\n      graduationDate\n      createdAt\n      updatedAt\n      program {\n        id\n        code\n        title\n        level\n        durationValue\n        durationUnit\n        school {\n          id\n          name\n        }\n      }\n      files {\n          id\n          originalName\n          mimeType\n          size\n          url\n          collection\n          createdAt\n        }\n      enrollments {\n        id\n        status\n        completionDate\n        dropDate\n        grade\n        points\n        curriculum {\n          id\n          year\n          course {\n            id\n            code\n            title\n            credits\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetStudentDetailsDocument,
    "\n  fragment StudentListFields on Student {\n    id\n    firstName\n    lastName\n    email\n    phone\n    applicationNumber\n    admissionNumber\n    studentNumber\n    status\n    applicationDate\n    admissionDate\n    rejectionDate\n    graduationDate\n    cgpa\n    creditsCompleted\n    program {\n      id\n      code\n      title\n      level\n      durationValue\n      durationUnit\n      school {\n        id\n        name\n      }\n    }\n  }\n": typeof types.StudentListFieldsFragmentDoc,
    "\n  query GetStudentsList($status: StudentStatus, $programId: ID) {\n    students(status: $status, programId: $programId, first: 100) {\n      edges {\n        node {\n          ...StudentListFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n  \n": typeof types.GetStudentsListDocument,
    "\n  query GetSchoolsAndPrograms {\n    schools(first: 100) {\n      edges {\n        node {\n          id\n          name\n        }\n      }\n    }\n    programs(first: 100) {\n      edges {\n        node {\n          id\n          title\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetSchoolsAndProgramsDocument,
    "\n  query GetSchoolsWithPrograms($first: Int = 10, $after: String) {\n    schools(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          name\n          description\n          programs {\n            id\n            code\n            title\n            level\n            durationValue\n            durationUnit\n            shortDescription\n            longDescription\n            requirements {\n              id\n              description\n              sortOrder\n            }\n          }\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": typeof types.GetSchoolsWithProgramsDocument,
    "\n  query GetLecturerPortal {\n    me {\n      id\n      lecturers {\n        id\n        firstName\n        lastName\n        curricula {\n          id\n          year\n          program {\n            id\n            code\n            title\n          }\n          course {\n            id\n            code\n            title\n          }\n          enrollments {\n            id\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetLecturerPortalDocument,
    "\n  query GetCurriculumPortal($id: ID!) {\n    curriculum(id: $id) {\n      id\n      year\n      program {\n        id\n        code\n        title\n        level\n      }\n      course {\n        id\n        code\n        title\n        description\n        credits\n      }\n      assessments {\n        id\n        title\n        description\n        type\n        term\n        weightPercentage\n        maxScore\n        dueDate\n        assessmentResults {\n          id\n          score\n          student {\n            id\n          }\n        }\n      }\n      enrollments {\n        id\n        student {\n          id\n          firstName\n          lastName\n        }\n      }\n    }\n  }\n": typeof types.GetCurriculumPortalDocument,
    "\n  query GetProgramsPageData($first: Int = 100) {\n    schools(first: $first) {\n      edges {\n        node {\n          id\n          name\n          description\n        }\n      }\n    }\n    programs(first: $first) {\n      edges {\n        node {\n          id\n          title\n          shortDescription\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetProgramsPageDataDocument,
    "\n  query GetProgramDetails($id: ID!) {\n    program(id: $id) {\n      id\n      code\n      title\n      level\n      durationValue\n      durationUnit\n      shortDescription\n      longDescription\n      requirements {\n        id\n        description\n        sortOrder\n      }\n      curricula {\n        id\n        year\n        course {\n          id\n          title\n          code\n          credits\n          school {\n            id\n            name\n          }\n        }\n      }\n      school {\n        id\n        name\n      }\n    }\n  }\n": typeof types.GetProgramDetailsDocument,
    "\n  query GetProgramOptions($first: Int = 100) {\n    programs(first: $first) {\n      edges {\n        node {\n          id\n          title\n        }\n      }\n    }\n  }\n": typeof types.GetProgramOptionsDocument,
    "\n  query GetCourseDetails {\n    me {\n      id\n      students {\n        id\n        enrollments {\n          id\n          curriculum {\n            id\n            course {\n              id\n              code\n              title\n              description\n              credits\n            }\n            lecturer {\n              id\n              firstName\n              lastName\n              user {\n                id\n                email\n              }\n            }\n            assessments {\n              id\n              title\n              description\n              type\n              term\n              weightPercentage\n              maxScore\n              assessmentResults {\n                id\n                score\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetCourseDetailsDocument,
    "\n  query GetStudentAcademics {\n    me {\n      id\n      students {\n        id\n        enrollments {\n          id\n          status\n          grade\n          curriculum {\n            id\n            year\n            course {\n              id\n              code\n              title\n              credits\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetStudentAcademicsDocument,
    "\n  query GetStudentPortal {\n    me {\n      id\n      email\n      students {\n        id\n        studentNumber\n        admissionNumber\n        applicationNumber\n        firstName\n        middleNames\n        lastName\n        email\n        phone\n        dob\n        address\n        emergencyContact\n        sex\n        maritalStatus\n        nationality\n        nrcNumber\n        passportNumber\n        intake\n        studyMode\n        status\n        applicationDate\n        admissionDate\n        graduationDate\n        cgpa\n        creditsCompleted\n        program {\n          id\n          code\n          title\n          level\n          durationValue\n          durationUnit\n        }\n        enrollments {\n          id\n          status\n          grade\n          curriculum {\n            id\n            year\n            course {\n              id\n              code\n              title\n              credits\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetStudentPortalDocument,
};
const documents: Documents = {
    "\n  query GetNotifications {\n    unreadNotificationsCount\n    notifications(first: 10) {\n      data {\n        id\n        read_at\n        created_at\n        data {\n          title\n          body\n          action_url\n          type\n        }\n      }\n    }\n  }\n": types.GetNotificationsDocument,
    "\n  mutation MarkNotificationAsRead($id: ID!) {\n    markNotificationAsRead(id: $id) {\n      id\n      read_at\n    }\n  }\n": types.MarkNotificationAsReadDocument,
    "\n  mutation MarkAllNotificationsAsRead {\n    markAllNotificationsAsRead\n  }\n": types.MarkAllNotificationsAsReadDocument,
    "\n  query GetMe {\n    me {\n      id\n      email\n      phone\n      applicants {\n        id\n        firstName\n        middleNames\n        lastName\n        email\n        phone\n      }\n      students {\n        id\n        status\n      }\n      admins {\n        id\n      }\n      lecturers {\n        id\n      }\n    }\n  }\n": types.GetMeDocument,
    "\n query GetAdminAccounts($first: Int = 100) { admins(first: $first) { edges { node { id employeeNumber department position createdAt updatedAt user { id } } } } }\n": types.GetAdminAccountsDocument,
    "\n  query GetAdminDashboardData($first: Int = 100) {\n    registeredStudents: students(status: REGISTERED, first: $first) {\n      edges { node { id } }\n    }\n    pendingApplications: students(status: PENDING, first: $first) {\n      edges { node { id } }\n    }\n    schools(first: $first) {\n      edges { node { id } }\n    }\n    programs(first: $first) {\n      edges { node { id } }\n    }\n  }\n": types.GetAdminDashboardDataDocument,
    "\n fragment AnnouncementFields on Announcement { id title content type targetLevel targetId targetName author authorUser { id } attachment { id\n          originalName\n          mimeType\n          size\n          url\n          collection\n          createdAt } createdAt updatedAt }\n": types.AnnouncementFieldsFragmentDoc,
    "\n query GetAnnouncementsList($type: AnnouncementType, $targetLevel: TargetLevel, $first: Int!) { announcements(type: $type, targetLevel: $targetLevel, first: $first) { edges { node { ...AnnouncementFields } } pageInfo { hasNextPage endCursor } } }\n \n": types.GetAnnouncementsListDocument,
    "\n query GetAnnouncementTargetOptions { schools(first: 100) { edges { node { id name } } } programs(first: 100) { edges { node { id title school { id name } } } } }\n": types.GetAnnouncementTargetOptionsDocument,
    "\n  query GetLecturerDetails($id: ID!) {\n    lecturer(id: $id) {\n      id\n      firstName\n      middleName\n      lastName\n      dob\n      address\n      emergencyContact\n      createdAt\n      updatedAt\n      school {\n        id\n        name\n      }\n      user {\n        id\n        email\n      }\n      curricula {\n        id\n        year\n        program {\n          id\n          title\n          code\n        }\n        course {\n          id\n          code\n          title\n          credits\n        }\n      }\n    }\n  }\n": types.GetLecturerDetailsDocument,
    "\n  fragment ManagementSchoolFields on School {\n    id\n    name\n    description\n    dean {\n      id\n      email\n    }\n  }\n": types.ManagementSchoolFieldsFragmentDoc,
    "\n  query GetManagement($first: Int = 100) {\n    schools(first: $first) {\n      edges {\n        node {\n          ...ManagementSchoolFields\n        }\n      }\n    }\n  }\n  \n": types.GetManagementDocument,
    "\n  query GetProgramDetail($id: ID!) {\n    program(id: $id) {\n      id\n      code\n      title\n      level\n      durationValue\n      durationUnit\n      shortDescription\n      longDescription\n      createdAt\n      updatedAt\n      requirements {\n        id\n        description\n        sortOrder\n      }\n      curricula {\n        id\n        year\n        course {\n          id\n          title\n          code\n          credits\n          school {\n            id\n            name\n          }\n        }\n        lecturer {\n          id\n          firstName\n          middleName\n          lastName\n          school {\n            id\n            name\n          }\n        }\n      }\n      school {\n        id\n        name\n      }\n    }\n  }\n": types.GetProgramDetailDocument,
    "\n  query GetAllCourses($first: Int = 1000) {\n    courses(first: $first) {\n      edges {\n        node {\n          id\n          code\n          title\n          credits\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetAllCoursesDocument,
    "\n  query GetAllLecturers($first: Int = 1000) {\n    lecturers(first: $first) {\n      edges {\n        node {\n          id\n          firstName\n          middleName\n          lastName\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetAllLecturersDocument,
    "\n  query GetResultsPage($first: Int = 100) {\n    courses(first: $first) {\n      edges {\n        node {\n          id\n          code\n          title\n          curricula {\n            id\n            year\n            assessments {\n              id\n              title\n              type\n              term\n              maxScore\n              weightPercentage\n              dueDate\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetResultsPageDocument,
    "\n  query GetSchoolDetails($id: ID!) {\n    school(id: $id) {\n      id\n      name\n      description\n      dean {\n        id\n        email\n      }\n      programs {\n        id\n        code\n        title\n        level\n        durationValue\n        durationUnit\n        shortDescription\n      }\n      courses {\n        id\n        code\n        title\n        description\n        credits\n      }\n      lecturers {\n        id\n        firstName\n        middleName\n        lastName\n        user {\n          id\n          email\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetSchoolDetailsDocument,
    "\n  query GetStudentDetails($id: ID!) {\n    student(id: $id) {\n      id\n      applicationNumber\n      admissionNumber\n      studentNumber\n      firstName\n      middleNames\n      lastName\n      email\n      phone\n      dob\n      address\n      emergencyContact\n      sex\n      maritalStatus\n      nationality\n      nrcNumber\n      passportNumber\n      intake\n      studyMode\n      status\n      cgpa\n      creditsCompleted\n      applicationDate\n      admissionDate\n      rejectionDate\n      graduationDate\n      createdAt\n      updatedAt\n      program {\n        id\n        code\n        title\n        level\n        durationValue\n        durationUnit\n        school {\n          id\n          name\n        }\n      }\n      files {\n          id\n          originalName\n          mimeType\n          size\n          url\n          collection\n          createdAt\n        }\n      enrollments {\n        id\n        status\n        completionDate\n        dropDate\n        grade\n        points\n        curriculum {\n          id\n          year\n          course {\n            id\n            code\n            title\n            credits\n          }\n        }\n      }\n    }\n  }\n": types.GetStudentDetailsDocument,
    "\n  fragment StudentListFields on Student {\n    id\n    firstName\n    lastName\n    email\n    phone\n    applicationNumber\n    admissionNumber\n    studentNumber\n    status\n    applicationDate\n    admissionDate\n    rejectionDate\n    graduationDate\n    cgpa\n    creditsCompleted\n    program {\n      id\n      code\n      title\n      level\n      durationValue\n      durationUnit\n      school {\n        id\n        name\n      }\n    }\n  }\n": types.StudentListFieldsFragmentDoc,
    "\n  query GetStudentsList($status: StudentStatus, $programId: ID) {\n    students(status: $status, programId: $programId, first: 100) {\n      edges {\n        node {\n          ...StudentListFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n  \n": types.GetStudentsListDocument,
    "\n  query GetSchoolsAndPrograms {\n    schools(first: 100) {\n      edges {\n        node {\n          id\n          name\n        }\n      }\n    }\n    programs(first: 100) {\n      edges {\n        node {\n          id\n          title\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetSchoolsAndProgramsDocument,
    "\n  query GetSchoolsWithPrograms($first: Int = 10, $after: String) {\n    schools(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          name\n          description\n          programs {\n            id\n            code\n            title\n            level\n            durationValue\n            durationUnit\n            shortDescription\n            longDescription\n            requirements {\n              id\n              description\n              sortOrder\n            }\n          }\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": types.GetSchoolsWithProgramsDocument,
    "\n  query GetLecturerPortal {\n    me {\n      id\n      lecturers {\n        id\n        firstName\n        lastName\n        curricula {\n          id\n          year\n          program {\n            id\n            code\n            title\n          }\n          course {\n            id\n            code\n            title\n          }\n          enrollments {\n            id\n          }\n        }\n      }\n    }\n  }\n": types.GetLecturerPortalDocument,
    "\n  query GetCurriculumPortal($id: ID!) {\n    curriculum(id: $id) {\n      id\n      year\n      program {\n        id\n        code\n        title\n        level\n      }\n      course {\n        id\n        code\n        title\n        description\n        credits\n      }\n      assessments {\n        id\n        title\n        description\n        type\n        term\n        weightPercentage\n        maxScore\n        dueDate\n        assessmentResults {\n          id\n          score\n          student {\n            id\n          }\n        }\n      }\n      enrollments {\n        id\n        student {\n          id\n          firstName\n          lastName\n        }\n      }\n    }\n  }\n": types.GetCurriculumPortalDocument,
    "\n  query GetProgramsPageData($first: Int = 100) {\n    schools(first: $first) {\n      edges {\n        node {\n          id\n          name\n          description\n        }\n      }\n    }\n    programs(first: $first) {\n      edges {\n        node {\n          id\n          title\n          shortDescription\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n": types.GetProgramsPageDataDocument,
    "\n  query GetProgramDetails($id: ID!) {\n    program(id: $id) {\n      id\n      code\n      title\n      level\n      durationValue\n      durationUnit\n      shortDescription\n      longDescription\n      requirements {\n        id\n        description\n        sortOrder\n      }\n      curricula {\n        id\n        year\n        course {\n          id\n          title\n          code\n          credits\n          school {\n            id\n            name\n          }\n        }\n      }\n      school {\n        id\n        name\n      }\n    }\n  }\n": types.GetProgramDetailsDocument,
    "\n  query GetProgramOptions($first: Int = 100) {\n    programs(first: $first) {\n      edges {\n        node {\n          id\n          title\n        }\n      }\n    }\n  }\n": types.GetProgramOptionsDocument,
    "\n  query GetCourseDetails {\n    me {\n      id\n      students {\n        id\n        enrollments {\n          id\n          curriculum {\n            id\n            course {\n              id\n              code\n              title\n              description\n              credits\n            }\n            lecturer {\n              id\n              firstName\n              lastName\n              user {\n                id\n                email\n              }\n            }\n            assessments {\n              id\n              title\n              description\n              type\n              term\n              weightPercentage\n              maxScore\n              assessmentResults {\n                id\n                score\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetCourseDetailsDocument,
    "\n  query GetStudentAcademics {\n    me {\n      id\n      students {\n        id\n        enrollments {\n          id\n          status\n          grade\n          curriculum {\n            id\n            year\n            course {\n              id\n              code\n              title\n              credits\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetStudentAcademicsDocument,
    "\n  query GetStudentPortal {\n    me {\n      id\n      email\n      students {\n        id\n        studentNumber\n        admissionNumber\n        applicationNumber\n        firstName\n        middleNames\n        lastName\n        email\n        phone\n        dob\n        address\n        emergencyContact\n        sex\n        maritalStatus\n        nationality\n        nrcNumber\n        passportNumber\n        intake\n        studyMode\n        status\n        applicationDate\n        admissionDate\n        graduationDate\n        cgpa\n        creditsCompleted\n        program {\n          id\n          code\n          title\n          level\n          durationValue\n          durationUnit\n        }\n        enrollments {\n          id\n          status\n          grade\n          curriculum {\n            id\n            year\n            course {\n              id\n              code\n              title\n              credits\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetStudentPortalDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetNotifications {\n    unreadNotificationsCount\n    notifications(first: 10) {\n      data {\n        id\n        read_at\n        created_at\n        data {\n          title\n          body\n          action_url\n          type\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetNotifications {\n    unreadNotificationsCount\n    notifications(first: 10) {\n      data {\n        id\n        read_at\n        created_at\n        data {\n          title\n          body\n          action_url\n          type\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation MarkNotificationAsRead($id: ID!) {\n    markNotificationAsRead(id: $id) {\n      id\n      read_at\n    }\n  }\n"): (typeof documents)["\n  mutation MarkNotificationAsRead($id: ID!) {\n    markNotificationAsRead(id: $id) {\n      id\n      read_at\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation MarkAllNotificationsAsRead {\n    markAllNotificationsAsRead\n  }\n"): (typeof documents)["\n  mutation MarkAllNotificationsAsRead {\n    markAllNotificationsAsRead\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetMe {\n    me {\n      id\n      email\n      phone\n      applicants {\n        id\n        firstName\n        middleNames\n        lastName\n        email\n        phone\n      }\n      students {\n        id\n        status\n      }\n      admins {\n        id\n      }\n      lecturers {\n        id\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetMe {\n    me {\n      id\n      email\n      phone\n      applicants {\n        id\n        firstName\n        middleNames\n        lastName\n        email\n        phone\n      }\n      students {\n        id\n        status\n      }\n      admins {\n        id\n      }\n      lecturers {\n        id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n query GetAdminAccounts($first: Int = 100) { admins(first: $first) { edges { node { id employeeNumber department position createdAt updatedAt user { id } } } } }\n"): (typeof documents)["\n query GetAdminAccounts($first: Int = 100) { admins(first: $first) { edges { node { id employeeNumber department position createdAt updatedAt user { id } } } } }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAdminDashboardData($first: Int = 100) {\n    registeredStudents: students(status: REGISTERED, first: $first) {\n      edges { node { id } }\n    }\n    pendingApplications: students(status: PENDING, first: $first) {\n      edges { node { id } }\n    }\n    schools(first: $first) {\n      edges { node { id } }\n    }\n    programs(first: $first) {\n      edges { node { id } }\n    }\n  }\n"): (typeof documents)["\n  query GetAdminDashboardData($first: Int = 100) {\n    registeredStudents: students(status: REGISTERED, first: $first) {\n      edges { node { id } }\n    }\n    pendingApplications: students(status: PENDING, first: $first) {\n      edges { node { id } }\n    }\n    schools(first: $first) {\n      edges { node { id } }\n    }\n    programs(first: $first) {\n      edges { node { id } }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n fragment AnnouncementFields on Announcement { id title content type targetLevel targetId targetName author authorUser { id } attachment { id\n          originalName\n          mimeType\n          size\n          url\n          collection\n          createdAt } createdAt updatedAt }\n"): (typeof documents)["\n fragment AnnouncementFields on Announcement { id title content type targetLevel targetId targetName author authorUser { id } attachment { id\n          originalName\n          mimeType\n          size\n          url\n          collection\n          createdAt } createdAt updatedAt }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n query GetAnnouncementsList($type: AnnouncementType, $targetLevel: TargetLevel, $first: Int!) { announcements(type: $type, targetLevel: $targetLevel, first: $first) { edges { node { ...AnnouncementFields } } pageInfo { hasNextPage endCursor } } }\n \n"): (typeof documents)["\n query GetAnnouncementsList($type: AnnouncementType, $targetLevel: TargetLevel, $first: Int!) { announcements(type: $type, targetLevel: $targetLevel, first: $first) { edges { node { ...AnnouncementFields } } pageInfo { hasNextPage endCursor } } }\n \n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n query GetAnnouncementTargetOptions { schools(first: 100) { edges { node { id name } } } programs(first: 100) { edges { node { id title school { id name } } } } }\n"): (typeof documents)["\n query GetAnnouncementTargetOptions { schools(first: 100) { edges { node { id name } } } programs(first: 100) { edges { node { id title school { id name } } } } }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetLecturerDetails($id: ID!) {\n    lecturer(id: $id) {\n      id\n      firstName\n      middleName\n      lastName\n      dob\n      address\n      emergencyContact\n      createdAt\n      updatedAt\n      school {\n        id\n        name\n      }\n      user {\n        id\n        email\n      }\n      curricula {\n        id\n        year\n        program {\n          id\n          title\n          code\n        }\n        course {\n          id\n          code\n          title\n          credits\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetLecturerDetails($id: ID!) {\n    lecturer(id: $id) {\n      id\n      firstName\n      middleName\n      lastName\n      dob\n      address\n      emergencyContact\n      createdAt\n      updatedAt\n      school {\n        id\n        name\n      }\n      user {\n        id\n        email\n      }\n      curricula {\n        id\n        year\n        program {\n          id\n          title\n          code\n        }\n        course {\n          id\n          code\n          title\n          credits\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment ManagementSchoolFields on School {\n    id\n    name\n    description\n    dean {\n      id\n      email\n    }\n  }\n"): (typeof documents)["\n  fragment ManagementSchoolFields on School {\n    id\n    name\n    description\n    dean {\n      id\n      email\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetManagement($first: Int = 100) {\n    schools(first: $first) {\n      edges {\n        node {\n          ...ManagementSchoolFields\n        }\n      }\n    }\n  }\n  \n"): (typeof documents)["\n  query GetManagement($first: Int = 100) {\n    schools(first: $first) {\n      edges {\n        node {\n          ...ManagementSchoolFields\n        }\n      }\n    }\n  }\n  \n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProgramDetail($id: ID!) {\n    program(id: $id) {\n      id\n      code\n      title\n      level\n      durationValue\n      durationUnit\n      shortDescription\n      longDescription\n      createdAt\n      updatedAt\n      requirements {\n        id\n        description\n        sortOrder\n      }\n      curricula {\n        id\n        year\n        course {\n          id\n          title\n          code\n          credits\n          school {\n            id\n            name\n          }\n        }\n        lecturer {\n          id\n          firstName\n          middleName\n          lastName\n          school {\n            id\n            name\n          }\n        }\n      }\n      school {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetProgramDetail($id: ID!) {\n    program(id: $id) {\n      id\n      code\n      title\n      level\n      durationValue\n      durationUnit\n      shortDescription\n      longDescription\n      createdAt\n      updatedAt\n      requirements {\n        id\n        description\n        sortOrder\n      }\n      curricula {\n        id\n        year\n        course {\n          id\n          title\n          code\n          credits\n          school {\n            id\n            name\n          }\n        }\n        lecturer {\n          id\n          firstName\n          middleName\n          lastName\n          school {\n            id\n            name\n          }\n        }\n      }\n      school {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAllCourses($first: Int = 1000) {\n    courses(first: $first) {\n      edges {\n        node {\n          id\n          code\n          title\n          credits\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetAllCourses($first: Int = 1000) {\n    courses(first: $first) {\n      edges {\n        node {\n          id\n          code\n          title\n          credits\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAllLecturers($first: Int = 1000) {\n    lecturers(first: $first) {\n      edges {\n        node {\n          id\n          firstName\n          middleName\n          lastName\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetAllLecturers($first: Int = 1000) {\n    lecturers(first: $first) {\n      edges {\n        node {\n          id\n          firstName\n          middleName\n          lastName\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetResultsPage($first: Int = 100) {\n    courses(first: $first) {\n      edges {\n        node {\n          id\n          code\n          title\n          curricula {\n            id\n            year\n            assessments {\n              id\n              title\n              type\n              term\n              maxScore\n              weightPercentage\n              dueDate\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetResultsPage($first: Int = 100) {\n    courses(first: $first) {\n      edges {\n        node {\n          id\n          code\n          title\n          curricula {\n            id\n            year\n            assessments {\n              id\n              title\n              type\n              term\n              maxScore\n              weightPercentage\n              dueDate\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSchoolDetails($id: ID!) {\n    school(id: $id) {\n      id\n      name\n      description\n      dean {\n        id\n        email\n      }\n      programs {\n        id\n        code\n        title\n        level\n        durationValue\n        durationUnit\n        shortDescription\n      }\n      courses {\n        id\n        code\n        title\n        description\n        credits\n      }\n      lecturers {\n        id\n        firstName\n        middleName\n        lastName\n        user {\n          id\n          email\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetSchoolDetails($id: ID!) {\n    school(id: $id) {\n      id\n      name\n      description\n      dean {\n        id\n        email\n      }\n      programs {\n        id\n        code\n        title\n        level\n        durationValue\n        durationUnit\n        shortDescription\n      }\n      courses {\n        id\n        code\n        title\n        description\n        credits\n      }\n      lecturers {\n        id\n        firstName\n        middleName\n        lastName\n        user {\n          id\n          email\n        }\n      }\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetStudentDetails($id: ID!) {\n    student(id: $id) {\n      id\n      applicationNumber\n      admissionNumber\n      studentNumber\n      firstName\n      middleNames\n      lastName\n      email\n      phone\n      dob\n      address\n      emergencyContact\n      sex\n      maritalStatus\n      nationality\n      nrcNumber\n      passportNumber\n      intake\n      studyMode\n      status\n      cgpa\n      creditsCompleted\n      applicationDate\n      admissionDate\n      rejectionDate\n      graduationDate\n      createdAt\n      updatedAt\n      program {\n        id\n        code\n        title\n        level\n        durationValue\n        durationUnit\n        school {\n          id\n          name\n        }\n      }\n      files {\n          id\n          originalName\n          mimeType\n          size\n          url\n          collection\n          createdAt\n        }\n      enrollments {\n        id\n        status\n        completionDate\n        dropDate\n        grade\n        points\n        curriculum {\n          id\n          year\n          course {\n            id\n            code\n            title\n            credits\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetStudentDetails($id: ID!) {\n    student(id: $id) {\n      id\n      applicationNumber\n      admissionNumber\n      studentNumber\n      firstName\n      middleNames\n      lastName\n      email\n      phone\n      dob\n      address\n      emergencyContact\n      sex\n      maritalStatus\n      nationality\n      nrcNumber\n      passportNumber\n      intake\n      studyMode\n      status\n      cgpa\n      creditsCompleted\n      applicationDate\n      admissionDate\n      rejectionDate\n      graduationDate\n      createdAt\n      updatedAt\n      program {\n        id\n        code\n        title\n        level\n        durationValue\n        durationUnit\n        school {\n          id\n          name\n        }\n      }\n      files {\n          id\n          originalName\n          mimeType\n          size\n          url\n          collection\n          createdAt\n        }\n      enrollments {\n        id\n        status\n        completionDate\n        dropDate\n        grade\n        points\n        curriculum {\n          id\n          year\n          course {\n            id\n            code\n            title\n            credits\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment StudentListFields on Student {\n    id\n    firstName\n    lastName\n    email\n    phone\n    applicationNumber\n    admissionNumber\n    studentNumber\n    status\n    applicationDate\n    admissionDate\n    rejectionDate\n    graduationDate\n    cgpa\n    creditsCompleted\n    program {\n      id\n      code\n      title\n      level\n      durationValue\n      durationUnit\n      school {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment StudentListFields on Student {\n    id\n    firstName\n    lastName\n    email\n    phone\n    applicationNumber\n    admissionNumber\n    studentNumber\n    status\n    applicationDate\n    admissionDate\n    rejectionDate\n    graduationDate\n    cgpa\n    creditsCompleted\n    program {\n      id\n      code\n      title\n      level\n      durationValue\n      durationUnit\n      school {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetStudentsList($status: StudentStatus, $programId: ID) {\n    students(status: $status, programId: $programId, first: 100) {\n      edges {\n        node {\n          ...StudentListFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n  \n"): (typeof documents)["\n  query GetStudentsList($status: StudentStatus, $programId: ID) {\n    students(status: $status, programId: $programId, first: 100) {\n      edges {\n        node {\n          ...StudentListFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n  \n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSchoolsAndPrograms {\n    schools(first: 100) {\n      edges {\n        node {\n          id\n          name\n        }\n      }\n    }\n    programs(first: 100) {\n      edges {\n        node {\n          id\n          title\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetSchoolsAndPrograms {\n    schools(first: 100) {\n      edges {\n        node {\n          id\n          name\n        }\n      }\n    }\n    programs(first: 100) {\n      edges {\n        node {\n          id\n          title\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetSchoolsWithPrograms($first: Int = 10, $after: String) {\n    schools(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          name\n          description\n          programs {\n            id\n            code\n            title\n            level\n            durationValue\n            durationUnit\n            shortDescription\n            longDescription\n            requirements {\n              id\n              description\n              sortOrder\n            }\n          }\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetSchoolsWithPrograms($first: Int = 10, $after: String) {\n    schools(first: $first, after: $after) {\n      edges {\n        node {\n          id\n          name\n          description\n          programs {\n            id\n            code\n            title\n            level\n            durationValue\n            durationUnit\n            shortDescription\n            longDescription\n            requirements {\n              id\n              description\n              sortOrder\n            }\n          }\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetLecturerPortal {\n    me {\n      id\n      lecturers {\n        id\n        firstName\n        lastName\n        curricula {\n          id\n          year\n          program {\n            id\n            code\n            title\n          }\n          course {\n            id\n            code\n            title\n          }\n          enrollments {\n            id\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetLecturerPortal {\n    me {\n      id\n      lecturers {\n        id\n        firstName\n        lastName\n        curricula {\n          id\n          year\n          program {\n            id\n            code\n            title\n          }\n          course {\n            id\n            code\n            title\n          }\n          enrollments {\n            id\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetCurriculumPortal($id: ID!) {\n    curriculum(id: $id) {\n      id\n      year\n      program {\n        id\n        code\n        title\n        level\n      }\n      course {\n        id\n        code\n        title\n        description\n        credits\n      }\n      assessments {\n        id\n        title\n        description\n        type\n        term\n        weightPercentage\n        maxScore\n        dueDate\n        assessmentResults {\n          id\n          score\n          student {\n            id\n          }\n        }\n      }\n      enrollments {\n        id\n        student {\n          id\n          firstName\n          lastName\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetCurriculumPortal($id: ID!) {\n    curriculum(id: $id) {\n      id\n      year\n      program {\n        id\n        code\n        title\n        level\n      }\n      course {\n        id\n        code\n        title\n        description\n        credits\n      }\n      assessments {\n        id\n        title\n        description\n        type\n        term\n        weightPercentage\n        maxScore\n        dueDate\n        assessmentResults {\n          id\n          score\n          student {\n            id\n          }\n        }\n      }\n      enrollments {\n        id\n        student {\n          id\n          firstName\n          lastName\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProgramsPageData($first: Int = 100) {\n    schools(first: $first) {\n      edges {\n        node {\n          id\n          name\n          description\n        }\n      }\n    }\n    programs(first: $first) {\n      edges {\n        node {\n          id\n          title\n          shortDescription\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetProgramsPageData($first: Int = 100) {\n    schools(first: $first) {\n      edges {\n        node {\n          id\n          name\n          description\n        }\n      }\n    }\n    programs(first: $first) {\n      edges {\n        node {\n          id\n          title\n          shortDescription\n          school {\n            id\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProgramDetails($id: ID!) {\n    program(id: $id) {\n      id\n      code\n      title\n      level\n      durationValue\n      durationUnit\n      shortDescription\n      longDescription\n      requirements {\n        id\n        description\n        sortOrder\n      }\n      curricula {\n        id\n        year\n        course {\n          id\n          title\n          code\n          credits\n          school {\n            id\n            name\n          }\n        }\n      }\n      school {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetProgramDetails($id: ID!) {\n    program(id: $id) {\n      id\n      code\n      title\n      level\n      durationValue\n      durationUnit\n      shortDescription\n      longDescription\n      requirements {\n        id\n        description\n        sortOrder\n      }\n      curricula {\n        id\n        year\n        course {\n          id\n          title\n          code\n          credits\n          school {\n            id\n            name\n          }\n        }\n      }\n      school {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProgramOptions($first: Int = 100) {\n    programs(first: $first) {\n      edges {\n        node {\n          id\n          title\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetProgramOptions($first: Int = 100) {\n    programs(first: $first) {\n      edges {\n        node {\n          id\n          title\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetCourseDetails {\n    me {\n      id\n      students {\n        id\n        enrollments {\n          id\n          curriculum {\n            id\n            course {\n              id\n              code\n              title\n              description\n              credits\n            }\n            lecturer {\n              id\n              firstName\n              lastName\n              user {\n                id\n                email\n              }\n            }\n            assessments {\n              id\n              title\n              description\n              type\n              term\n              weightPercentage\n              maxScore\n              assessmentResults {\n                id\n                score\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetCourseDetails {\n    me {\n      id\n      students {\n        id\n        enrollments {\n          id\n          curriculum {\n            id\n            course {\n              id\n              code\n              title\n              description\n              credits\n            }\n            lecturer {\n              id\n              firstName\n              lastName\n              user {\n                id\n                email\n              }\n            }\n            assessments {\n              id\n              title\n              description\n              type\n              term\n              weightPercentage\n              maxScore\n              assessmentResults {\n                id\n                score\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetStudentAcademics {\n    me {\n      id\n      students {\n        id\n        enrollments {\n          id\n          status\n          grade\n          curriculum {\n            id\n            year\n            course {\n              id\n              code\n              title\n              credits\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetStudentAcademics {\n    me {\n      id\n      students {\n        id\n        enrollments {\n          id\n          status\n          grade\n          curriculum {\n            id\n            year\n            course {\n              id\n              code\n              title\n              credits\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetStudentPortal {\n    me {\n      id\n      email\n      students {\n        id\n        studentNumber\n        admissionNumber\n        applicationNumber\n        firstName\n        middleNames\n        lastName\n        email\n        phone\n        dob\n        address\n        emergencyContact\n        sex\n        maritalStatus\n        nationality\n        nrcNumber\n        passportNumber\n        intake\n        studyMode\n        status\n        applicationDate\n        admissionDate\n        graduationDate\n        cgpa\n        creditsCompleted\n        program {\n          id\n          code\n          title\n          level\n          durationValue\n          durationUnit\n        }\n        enrollments {\n          id\n          status\n          grade\n          curriculum {\n            id\n            year\n            course {\n              id\n              code\n              title\n              credits\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetStudentPortal {\n    me {\n      id\n      email\n      students {\n        id\n        studentNumber\n        admissionNumber\n        applicationNumber\n        firstName\n        middleNames\n        lastName\n        email\n        phone\n        dob\n        address\n        emergencyContact\n        sex\n        maritalStatus\n        nationality\n        nrcNumber\n        passportNumber\n        intake\n        studyMode\n        status\n        applicationDate\n        admissionDate\n        graduationDate\n        cgpa\n        creditsCompleted\n        program {\n          id\n          code\n          title\n          level\n          durationValue\n          durationUnit\n        }\n        enrollments {\n          id\n          status\n          grade\n          curriculum {\n            id\n            year\n            course {\n              id\n              code\n              title\n              credits\n            }\n          }\n        }\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;